CREATE TABLE CATEGORIA (
	ID					INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT "Clave primaria del registro. Valor autogenerado.", 
	CODIGO 				CHAR(10) NOT NULL UNIQUE COMMENT "Código de identificación del CATEGORIA. Clave única.", 
	DESCRIPCION			CHAR(100) NOT NULL COMMENT "Descripción de la categoría"
);

CREATE TABLE AUTOR (
	ID					INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT "Clave primaria del registro. Valor autogenerado.", 
	IDENTIFICADOR		CHAR(10) NOT NULL UNIQUE COMMENT "Código de identificación del autor. Clave única.", 
	NOMBRE 				CHAR(100) NOT NULL COMMENT "Nombre del autor.",
	APELLIDOS			CHAR(100) NOT NULL COMMENT "Apellidos del autor.",
	NACIONALIDAD		CHAR(100) NOT NULL COMMENT "Nacionalidad del autor."
	
);

CREATE TABLE LIBRO (
	ID					INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT "Clave primaria del registro. Valor autogenerado.", 
	-- No es necesario porque tenemos el ISBB 				CODIGO 				CHAR(10) NOT NULL UNIQUE COMMENT "Código de identificación del libro. Clave única.",	
	ISBN				CHAR(100) NOT NULL UNIQUE COMMENT "ISBN del libro.",
	TITULO				CHAR(50) NOT NULL COMMENT "Título del libro", 
	EDITORIAL			CHAR(50) NOT NULL COMMENT "Editorial a la que pertenece el libro.",
	ID_CATEGORIA		INT NOT NULL COMMENT "Clave ajena a la tabla CATEGORIA.",
	ID_AUTOR			INT NOT NULL COMMENT "Clave ajena a la tabla AUTOR.",
	
	FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID),
	FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR(ID)
);

CREATE TABLE COPIA (
	ID					INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT "Clave primaria del registro. Valor autogenerado.", 
	CODIGO 				CHAR(10) NOT NULL UNIQUE COMMENT "Código de identificación de la copia. Clave única.", 
	ESTADO 				CHAR(15) NOT NULL COMMENT "Estado de la copia.",
	ID_LIBRO			INT NOT NULL COMMENT "Clave ajena a la tabla LIBRO.",
	
	FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO(ID)
);

CREATE TABLE USUARIO (
	ID					INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT "Clave primaria del registro. Valor autogenerado.", 
	IDENTIFICADOR		CHAR(10) NOT NULL UNIQUE COMMENT "Código de identificación del usuario. Clave única.", 
	NOMBRE 				CHAR(100) NOT NULL COMMENT "Nombre del usuario.",
	APELLIDOS			CHAR(100) NOT NULL COMMENT "Apellidos del usuario."
);

CREATE TABLE PRESTAMO (
	ID					INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT "Clave primaria del registro. Valor autogenerado.", 
	FECHA_INICIO		DATE NOT NULL COMMENT "Fecha de comienzo del préstamo",
	FECHA_FIN			DATE COMMENT "Fecha de fin del préstamo",
	ID_USUARIO			INT NOT NULL COMMENT "Clave ajena a la tabla USUARIO.",
	ID_COPIA			INT NOT NULL COMMENT "Clave ajena a la tabla COPIA.",
	
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY (ID_COPIA) REFERENCES COPIA(ID)
);

INSERT INTO CATEGORIA (CODIGO,DESCRIPCION) VALUES ("CAT01","FANTASIA");
INSERT INTO CATEGORIA (CODIGO,DESCRIPCION) VALUES ("CAT02","CIENCIA FICCION");
INSERT INTO CATEGORIA (CODIGO,DESCRIPCION) VALUES ("CAT03","ENSAYO");

INSERT INTO AUTOR (IDENTIFICADOR,NOMBRE,APELLIDOS,NACIONALIDAD) VALUES ("AUTOR01","MIGUEL","DELIBES","ESPAÑOLA");
INSERT INTO AUTOR (IDENTIFICADOR,NOMBRE,APELLIDOS,NACIONALIDAD) VALUES ("AUTOR02","BRANDON","SANDERSON","NORTE AMERICANA");
INSERT INTO AUTOR (IDENTIFICADOR,NOMBRE,APELLIDOS,NACIONALIDAD) VALUES ("AUTOR03","J.R.R","TOLKIEN","BRITANICA");

INSERT INTO LIBRO (ISBN,TITULO,EDITORIAL,ID_CATEGORIA,ID_AUTOR) VALUES ("LIBRO01","ELANTRIS","MINOTAURO",1,2);
INSERT INTO LIBRO (ISBN,TITULO,EDITORIAL,ID_CATEGORIA,ID_AUTOR) VALUES ("LIBRO02","NACIDOS DE LA BRUMA","MINOTAURO",2,2);
INSERT INTO LIBRO (ISBN,TITULO,EDITORIAL,ID_CATEGORIA,ID_AUTOR) VALUES ("LIBRO03","EL HOBBIT","ALFAGUARA",1,3);

INSERT INTO COPIA (CODIGO,ESTADO,ID_LIBRO) VALUES ("COPIA01","LIBRE",1);
INSERT INTO COPIA (CODIGO,ESTADO,ID_LIBRO) VALUES ("COPIA02","REPARACION",1);
INSERT INTO COPIA (CODIGO,ESTADO,ID_LIBRO) VALUES ("COPIA03","LIBRE",2);
INSERT INTO COPIA (CODIGO,ESTADO,ID_LIBRO) VALUES ("COPIA04","LIBRE",3);

INSERT INTO USUARIO (IDENTIFICADOR,NOMBRE,APELLIDOS) VALUES("USUARIO01","PEDRO","PEREZ");
INSERT INTO USUARIO (IDENTIFICADOR,NOMBRE,APELLIDOS) VALUES("USUARIO02","ANTONIO","MARTINEZ");
INSERT INTO USUARIO (IDENTIFICADOR,NOMBRE,APELLIDOS) VALUES("USUARIO03","LUCIA","SANCHEZ");

INSERT INTO PRESTAMO (FECHA_INICIO,FECHA_FIN,ID_USUARIO,ID_COPIA) VALUES (STR_TO_DATE('2021-10-21', '%Y-%m-%d'),STR_TO_DATE('2021-10-23', '%Y-%m-%d'),1,1);
INSERT INTO PRESTAMO (FECHA_INICIO,FECHA_FIN,ID_USUARIO,ID_COPIA) VALUES (STR_TO_DATE('2022-04-05', '%Y-%m-%d'),NULL,2,3);
INSERT INTO PRESTAMO (FECHA_INICIO,FECHA_FIN,ID_USUARIO,ID_COPIA) VALUES (STR_TO_DATE('2022-03-05', '%Y-%m-%d'),STR_TO_DATE('2022-03-07', '%Y-%m-%d'),3,4);


